// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YoutubeShareData.Models
{
    public partial class YsVideo
    {
        public int Id { get; set; }
        public string VideoLink { get; set; }
    }
}